In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

## Data understanding

https://www.kaggle.com/datasets/gregorut/videogamesales

In [49]:
df = pd.read_csv('./data/vgsales.csv')

# keeping only the needed features
df = df[['Name', 'Platform', 'Genre', 'Publisher']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Name       16598 non-null  object
 1   Platform   16598 non-null  object
 2   Genre      16598 non-null  object
 3   Publisher  16540 non-null  object
dtypes: object(4)
memory usage: 518.8+ KB


In [50]:
df.nunique()

Name         11493
Platform        31
Genre           12
Publisher      578
dtype: int64

In [51]:
# checking for null values
df.isna().sum()

Name          0
Platform      0
Genre         0
Publisher    58
dtype: int64

In [52]:
df[df.isna().any(axis=1)]

Name Platform  \
470                           wwe Smackdown vs. Raw 2006      PS2   
1303                                      Triple Play 99       PS   
1662        Shrek / Shrek 2 2-in-1 Gameboy Advance Video      GBA   
2222                                  Bentley's Hackpack      GBA   
3159   Nicktoons Collection: Game Boy Advance Video V...      GBA   
3166   SpongeBob SquarePants: Game Boy Advance Video ...      GBA   
3766   SpongeBob SquarePants: Game Boy Advance Video ...      GBA   
4145                                  Sonic the Hedgehog      PS3   
4526   The Fairly Odd Parents: Game Boy Advance Video...      GBA   
4635   The Fairly Odd Parents: Game Boy Advance Video...      GBA   
5302       Dragon Ball Z: Budokai Tenkaichi 2 (JP sales)      Wii   
5647   Cartoon Network Collection: Game Boy Advance V...      GBA   
6272   The Legend of Zelda: The Minish Cap(weekly JP ...      GBA   
6437            Sonic X: Game Boy Advance Video Volume 1      GBA   
6562   Dora the Explorer: Game Boy Advance Video Volu...      GBA   
6648   Cartoon Network Collection: Game Boy Advance V...      GBA   
6849      All Grown Up!: Game Boy Advance Video Volume 1      GBA   
7208   Nicktoons Collection: Game Boy Advance Video V...      GBA   
7351                      Yu Yu Hakusho: Dark Tournament      PS2   
7470   SpongeBob SquarePants: Game Boy Advance Video ...      GBA   
7953                    Thomas the Tank Engine & Friends      GBA   
8330     Dragon Ball GT: Game Boy Advance Video Volume 1      GBA   
8341   Codename: Kids Next Door: Game Boy Advance Vid...      GBA   
8368   Teenage Mutant Ninja Turtles: Game Boy Advance...      GBA   
8503                                        Stronghold 3       PC   
8770   Cartoon Network Collection: Game Boy Advance V...      GBA   
8848   Pokémon: Johto Photo Finish: Game Boy Advance ...      GBA   
8896   Strawberry Shortcake: Game Boy Advance Video V...      GBA   
9517                              Farming Simulator 2011       PC   
9749   Super Robot Wars OG Saga: Masou Kishin II - Re...      PSP   
10382                   Disney Channel Collection Vol. 1      GBA   
10494             Atsumare! Power Pro Kun no DS Koushien       DS   
11076                       Action Man-Operation Extreme       PS   
11526  Cartoon Network Collection: Game Boy Advance V...      GBA   
12487                               Chou Soujuu Mecha MG       DS   
12517       Prinny: Can I Really Be The Hero? (US sales)      PSP   
13278                     Monster Hunter Frontier Online      PS3   
13672                          B.L.U.E.: Legend of Water       PS   
13962                                     World of Tanks     X360   
14087                                       Housekeeping       DS   
14296                                Bikkuriman Daijiten       DS   
14311                                      Silverlicious       DS   
14698                                 UK Truck Simulator       PC   
14942  Umineko no Naku Koro ni San: Shinjitsu to Gens...      PS3   
15056                                            Xia-Xia       DS   
15261                                       Mario Tennis      3DS   
15325  Nicktoons Collection: Game Boy Advance Video V...      GBA   
15353                   Demolition Company: Gold Edition       PC   
15788  Moshi, Kono Sekai ni Kami-sama ga Iru to suru ...      PSV   
15915                                       Dream Dancer       DS   
16191                    Homeworld Remastered Collection       PC   
16198             AKB1/48: Idol to Guam de Koishitara...     X360   
16208  Super Robot Monkey Team: Game Boy Advance Vide...      GBA   
16229                        Brothers in Arms: Furious 4     X360   
16367                                  Dance with Devils      PSV   
16494                    Legends of Oz: Dorothy's Return      3DS   
16543                             Driving Simulator 2011       PC   
16553                                     Bound By

games with null values on Publisher column, they have 'Game Boy Advance Video Volume' in the name, so they are not actually games, those are tv shows sold to be played on the gameboy console, will drop those

## Data Preparation
**Cleaning**

In [53]:
# droping null values
df.dropna(inplace=True)

In [59]:
df

Name Platform  \
0                                            Wii Sports      Wii   
1                                     Super Mario Bros.      NES   
2                                        Mario Kart Wii      Wii   
3                                     Wii Sports Resort      Wii   
4                              Pokemon Red/Pokemon Blue       GB   
...                                                 ...      ...   
16593                Woody Woodpecker in Crazy Castle 5      GBA   
16594                     Men in Black II: Alien Escape       GC   
16595  SCORE International Baja 1000: The Official Game      PS2   
16596                                        Know How 2       DS   
16597                                  Spirits & Spells      GBA   

              Genre   Publisher         combined_features  
0            Sports    Nintendo       Wii Sports Nintendo  
1          Platform    Nintendo     NES Platform Nintendo  
2            Racing    Nintendo       Wii Racing Nintendo  
3            Sports    Nintendo       Wii Sports Nintendo  
4      Role-Playing    Nintendo  GB Role-Playing Nintendo  
...             ...         ...                       ...  
16593      Platform       Kemco        GBA Platform Kemco  
16594       Shooter  Infogrames     GC Shooter Infogrames  
16595        Racing  Activision     PS2 Racing Activision  
16596        Puzzle    7G//AMES        DS Puzzle 7G//AMES  
16597      Platform     Wanadoo      GBA Platform Wanadoo  

[16540 rows x 5 columns]

In [55]:
def combined_features(row):
    return row['Platform']+" "+row['Genre']+" "+row['Publisher']
df["combined_features"] = df.apply(combined_features, axis =1)

In [57]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [58]:
cosine_sim = cosine_similarity(count_matrix)

In [72]:
games_user_likes = "Mario Kart Wii"
def get_index_from_title(title):
    return df[df.Name == title].index.values[0]
games_index = get_index_from_title(games_user_likes)

In [73]:
similar_games = list(enumerate(cosine_sim[games_index]))

In [74]:
sorted_similar_games = sorted(similar_games, key=lambda x:x[1], reverse=True)

In [75]:
def get_title_from_index(index):
    return df[df.index == index]["Name"].values[0]
i=0
for game in sorted_similar_games:
    print(get_title_from_index(game[0]))
    i=i+1
    if i>15:
        break

Mario Kart Wii
LEGO Dimensions
Tiger Woods PGA Tour 08
One Piece Unlimited Cruise 1: The Treasure Beneath the Waves
Wii Sports
Wii Sports Resort
Wii Play
New Super Mario Bros. Wii
Mario Kart DS
Wii Fit
Wii Fit Plus
Super Smash Bros. Brawl
Mario Kart 7
Super Mario Galaxy
Mario Kart 64
Super Mario Kart
